### ISSUE TITLE
Custom runner class AndroidJUnit4 should have a public constructor with signature AndroidJUnit4(Class testClass)

### ISSUE THREAD

**Issue by ShagunParikh** [googlesamples/android-testing#58] opened 2015-09-29 05:54 UTC
Hi, I Have created the exact same test class as "CalculatorTest.java".. But when i am trying to run from Android studio, i am facing the following exception.. 

java.lang.Exception: Custom runner class AndroidJUnit4 should have a public constructor with signature AndroidJUnit4(Class testClass)
	at org.junit.runners.model.InitializationError.<init>(InitializationError.java:38)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:111)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:102)
	at org.junit.runners.Suite.<init>(Suite.java:70)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Please Help...

**Comment by cdsap** [comment] 2015-10-02 10:46
Hi @ShagunParikh 
I just tested the project and works well. 
Can you provide more details about your code and conf?

**Comment by oleg404** [comment] 2015-10-12 07:14
+1

**Comment by slinzner** [comment] 2015-11-03 16:28
I'm closing this issue since neither i nor folks in this thread can reproduce the issue. Please reopen or sent us a pull request if you think this is still an issue. Thanks.

**Closed by slinzner** 2015-11-03 16:28 UTC

**Comment by MuhammedRefaat** [comment] 2016-11-17 03:06
I have the exact same problem
